import{a as d,S as g,i as l}from"./assets/vendor-D8hBcPQM.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const s of t.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&i(s)}).observe(document,{childList:!0,subtree:!0});function r(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=r(e);fetch(e.href,t)}})();const h="https://pixabay.com/api/",y="52578833-1380a7e48419fcc1cc100434d";function b(o){const n={key:y,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:40};return d.get(h,{params:n}).then(r=>r.data)}const f=document.getElementById("gallery"),a=document.getElementById("loader"),L=new g(".gallery a",{captions:!0,captionsData:"alt",captionDelay:250});function E(o){if(!Array.isArray(o)||o.length===0)return;const n=o.map(r=>{const{webformatURL:i,largeImageURL:e,tags:t,likes:s,views:p,comments:u,downloads:m}=r;return`
<li class="photo-card">
  <a href="${e}" class="gallery-link" aria-label="${t}">
    <img src="${i}" alt="${t}" loading="lazy" />
  </a>
  <div class="info">
    <p class="info-item"><b>Likes</b><span>${s}</span></p>
    <p class="info-item"><b>Views</b><span>${p}</span></p>
    <p class="info-item"><b>Comments</b><span>${u}</span></p>
    <p class="info-item"><b>Downloads</b><span>${m}</span></p>
  </div>
</li>`}).join("");f.insertAdjacentHTML("beforeend",n),L.refresh()}function v(){f.innerHTML=""}function w(){a&&a.classList.add("is-active")}function I(){a&&a.classList.remove("is-active")}const A=document.getElementById("search-form"),c=document.getElementById("search-text");A.addEventListener("submit",P);function P(o){o.preventDefault();const n=c.value.trim();if(n===""){l.warning({title:"Warning",message:"Please enter a search term.",position:"topRight"});return}w(),v(),b(n).then(r=>{if(!r||!Array.isArray(r.hits))throw new Error("Invalid response from server");if(r.hits.length===0){l.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}E(r.hits)}).catch(r=>{console.error("Error fetching images:",r),l.error({title:"Error",message:"Something went wrong while fetching images. Please try later.",position:"topRight"})}).finally(()=>{I(),c.value=""})}
//# sourceMappingURL=index.js.map
